# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.22'

  #   - name: Build binaries
  #     run: go build -v ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker containers
      run: docker-compose up -d
    
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Run test
      run: go test -race ./...
